export default {
    'about.banner.author': 'The Future-Friendly Manifesto by Brad Frost',
    'about.banner.quote': '“Disruption will only accelerate. The quantity and diversity of connected devices — many of which we haven’t imagined yet — will explode, as will the quantity and diversity of the people around the world who use them. Our existing standards, workflows, and infrastructure won’t hold up. Today’s onslaught of devices is already pushing them to the breaking point. They can’t withstand what’s ahead.”',
    'about.hero.title': 'We Believe in Making the Universe Better',
    'about.hero.subtitle': 'Our mission is to empower every individual and business by optimizing and developing comprehensive solutions; we will reshape industries for the good of humanity',
    'about.hero.button.label': 'Read Our Story',
    'about.story.content': 'To you, reader, this company is created, not for financial or political gain, but for the betterment of humanity.\n\nAt the present, in this Austin Starbucks Reserve coffee shop I sit in and out in the world, humankind is in a crisis of identity. I look around and I see aimlessness in the eyes of individuals when, instead, there should be vision and vigor. Instead, there should be collaboration and optimization toward something far greater - to the personal freedom for each woman and man.\n\nTechnology, like most anything has both a positive and negative effect on society. And like most things, it must be taken in moderation. Fusion Technology is the first organization I will create. It\'s focus is on technology to connect the world we live in with a moral foundation. The organization creates the technological standards that all other organizations under this umbrella will use.\n\nCompanies - big and small - have started their journeys wrong. Quickness is necesssary, but it creates a less firm foundation - compromise does not bring about the best ends. It is much like the crisis found in programming. Programming is made up of so many different languages all with various purposes and optimizations. Instead, a universal sequence of langauges from the machine code to the high-level is more optimal where both the hardware and software could more easily be improved. To help build new companies and accelerate transformations of others, Fusion Consulting is the second organization.\n\nLook around. Every media outlet has a bias and each one is manipulating the content they share based off their viewership and ratings instead of what really matters - truth. Since there are no unbiased news organizations, Fusion Media is the third organization. This organization is responsible for spreading the truth with integrity and logic instead of emotion.\n\nToday, wealth is one of many keys to personal freedom. Fusion Finance is the fourth organization and will focus on delivering optimal financial solutions for saving, investing, banking, and planning for both individuals and businesses. It will also focus on the financials for Fusion as a whole.\n\nLegal Health Transport A.I. Cosmos',
    'about.story.subtitle': 'The Fusion Standard written by Ross Sheppard on October 1, 2018.',
    'about.story.title': 'Our Story',
    'about.values.title': 'Our Values',
    'about.values[0].title': 'Innovators at Heart',
    'about.values[0].subtitle': 'Approach innovation with a structured thought process',
    'about.values[0].description': 'By pushing the boundaries of technology through questioning, self-motivation, and problem solving, you are an innovator at heart. Each innovator at heart is relentless in his or her journey from ideation to production. True innovators care not about fame, power, or glory, but humanity.',
    'about.values[1].title': 'Bias for Action',
    'about.values[1].subtitle': 'Anticipate and respond to opportunities to improve',
    'about.values[1].description': 'Having a bias for action means you take action and get projects and solutions completed efficiently. You spend more time executing, learning, and improving. You encourage and require those around you to think strategically but act quickly.',
    'about.values[2].title': 'Challenge Respectfully',
    'about.values[2].subtitle': 'Generate ideas that challenge the status quo',
    'about.values[2].description': 'Challenge ideas so that better ones are borne from them. This means that here at fusion, we understand that improvement can always happen and our work is never done. Every person is open to challenges and because of that, innovation is spurred.',
    'about.values[3].title': 'Bias for Action',
    'about.values[3].subtitle': 'Anticipate and respond to opportunities to improve',
    'about.values[3].description': 'Having a bias for action means you take action and get projects and solutions completed efficiently. You spend more time executing, learning, and improving. You encourage and require those around you to think strategically but act quickly.',
    'about.values[4].title': 'Be Compassionate',
    'about.values[4].subtitle': 'Every moment is an opportunity to improve lives',
    'about.values[4].description': 'Integrity is paramount at Fusion. We believe in compassion and that is what brings people together, inspires people to win, and propels humanity forward.',
    'about.values[5].title': 'Collaborate Efficiently',
    'about.values[5].subtitle': 'Form meaningful relationships and produce results together',
    'about.values[5].description': 'We are a company full of caring, creative, brilliant people, and we put our heart into everything we do. We value effectiveness and will always improve upon improving.',

    'career.location.descriptor': 'Location',
    'career.requisition.descriptor': 'Requisition ID',

    'careers.title': 'Open Requisitions',
    'careers.filter.title': 'Filter',
    'careers.filter.location.label': 'Location',
    'careers.filter.org.label': 'Organization',
    'careers.filter.team.label': 'Team',
    'careers.search.placeholder': 'Search jobs...',
    'careers.search.none.descriptor': 'No roles available',
    'careers.search.end.descriptor': 'End of results',
    'careers.select.descriptor': 'More',
    'careers.table.header[0]': 'Role',
    'careers.table.header[1]': 'Organization',
    'careers.table.header[2]': 'Team',
    'careers.table.header[3]': 'Location',
    'careers.table.header[4]': ' ',
    'careers.team[0].title': 'Engineering & Technology',
    'careers.team[0].content': 'Develop solutions and provide professional services for businesses.',
    'careers.team[0].button[0]': 'Learn more',
    'careers.team[0].button[1]': 'See jobs',
    'careers.team[1].title': 'User Experience & Design',
    'careers.team[1].content': 'Create intuitive experiences and design the future of user interaction.',
    'careers.team[1].button[0]': 'Learn more',
    'careers.team[1].button[1]': 'See jobs',
    'careers.team[2].title': 'Accounts & Sales',
    'careers.team[2].content': 'Find, grow, and lead the people who make Fusion great.',
    'careers.team[2].button[0]': 'Learn more',
    'careers.team[2].button[1]': 'See jobs',
    'careers.team[3].title': 'Finance',
    'careers.team[3].content': 'Drive high impact revenues and provide guidance for investment decisions.',
    'careers.team[3].button[0]': 'Learn more',
    'careers.team[3].button[1]': 'See jobs',
    'careers.team[4].title': 'Marketing',
    'careers.team[4].content': 'Protect, enhance and build our company reputation through media.',
    'careers.team[4].button[0]': 'Learn more',
    'careers.team[4].button[1]': 'See jobs',
    'careers.team[5].title': 'Legal & Corporate Affairs',
    'careers.team[5].content': 'Optimize industry policy and govern how stakeholders interact with each other.',
    'careers.team[5].button[0]': 'Learn more',
    'careers.team[5].button[1]': 'See jobs',

    'company.cookies': 'Cookies',
    'company.copyright': 'Copyright 2018 Fusion Industries, Inc.',
    'company.description': '',
    'company.social.descriptor': 'FOLLOW FUSION',
    'company.privacy': 'Privacy',
    'company.sitemap': 'Sitemap',
    'company.terms': 'Terms Of Use',
    'company.name': 'Fusion Industries',
    'company.shortname': 'FUSION',
    'company.slogan': 'Optimizing business through intelligent design',

    'contact.form.subtitle': 'Fill out the form below and we\'ll put you in contact with one of our account representatives',
    'contact.form.title': 'Contact Us',
    'contact.locations.title': 'Our Locations',
    
    'home.hero.button[0].label': 'Who We Are',
    'home.hero.button[1].label': 'View Our Strategy',
    'home.logo[0].name': 'A.I.',
    'home.logo[1].name': 'Consulting',
    'home.logo[2].name': 'Cosmos',
    'home.logo[3].name': 'Energy',
    'home.logo[4].name': 'Finance',
    'home.logo[5].name': 'Health',
    'home.logo[6].name': 'Legal',
    'home.logo[7].name': 'Media',
    'home.logo[8].name': 'Technology',
    'home.logo[9].name': 'Transport',
    'home.overview.title': 'Together, we accelerate innovation',
    'home.overview.subtitle': ' ',
    'home.overview.card[0].title': 'Who We Are',
    'home.overview.card[0].button': 'About Us',
    'home.overview.card[0].content': 'Fusion redefines operational efficiency with solutions that transform. We are a team of innovative individuals who provide insights and deliver solutions across varying verticals.',
    'home.overview.card[1].title': 'Insights Engine',
    'home.overview.card[1].button': 'Read More',
    'home.overview.card[1].content': 'Business outcomes must be built faster than ever before. Our Insight Engine lets you discover end-to-end solutions and solve the complexities of your digital enterprise.',
    'home.overview.card[2].title': 'Contact Us',
    'home.overview.card[2].button': 'Our Locations',
    'home.overview.card[2].content': 'Our Accounts Team has vision and tactics for delivering optimal solutions. They work closely to provide you with the best technology and people possible.',
    'home.products.title': 'Solutions That Transform',
    'home.products.subtitle': 'A solution portfolio that optimizes infrastructure and delivery',
    'home.products[0].subtitle': 'A React Component Library',
    'home.products[0].title': 'Design System',
    'home.products[1].subtitle': 'Full Fledged JavaScript Solution',
    'home.products[1].title': 'Isomorph.io',
    'home.products[2].subtitle': 'Optimally built teams',
    'home.products[2].title': 'Professional Services',

    'insights.search.none.button': 'Go Home',
    'insights.search.none.descriptor': 'No insight articles could be found',
    'insights.search.placeholder': 'Search insights...',
    'insights.trending.title': 'Trending',

    'teams.team[0].about.descriptor': 'About User Experience & Design',
    'teams.team[0].description': 'Join our User Experience & Design Team to improve the overall experience of users by creating seamless interactive and dynamic experiences and desigining intuitive presentations of websites. By doing this, you are providing the maximum consumer satisfaction for all users.',
    'teams.team[0].name': 'User Experience & Design',
    'teams.team[0].slogan': 'Everything is designed, but we design things well',
    'teams.team[1].about.descriptor': 'About Finance',
    'teams.team[1].description': 'Finance',
    'teams.team[1].name': 'Finance',
    'teams.team[1].slogan': 'Make innovations a reality',
    'teams.team[2].about.descriptor': 'About Engineering & Technology',
    'teams.team[2].description': 'Be at the forefront of technology and work on projects like Isomorph.io and Fusion.design. Individuals who work in the Engineering and Technology Group offer innovative solutions that are expectionally well-thought out in terms of scale, cohesion, and coupling.',
    'teams.team[2].name': 'Engineering & Technology',
    'teams.team[2].slogan': 'We are in a position to change the world, not just study it',
    'teams.team[3].about.descriptor': 'About Legal & Corporate Affairs',
    'teams.team[3].description': ' ',
    'teams.team[3].name': 'Legal & Corporate Affairs',
    'teams.team[3].slogan': ' ',
    'teams.team[4].about.descriptor': 'About Marketing',
    'teams.team[4].description': ' ',
    'teams.team[4].name': 'Marketing',
    'teams.team[4].slogan': ' ',
    'teams.team[5].about.descriptor': 'About Accounts & Sales',
    'teams.team[5].description': ' ',
    'teams.team[5].name': 'Accounts & Sales',
    'teams.team[5].slogan': ' ',
    'teams.team.button.label': 'See jobs',
    'teams.team.roles.descriptor': 'Our Roles',

    // Consulting
    'consult.org.name': 'Fusion Consulting',
    'consult.org.slogan': '',
    'consult.home.banner.button[0].label': 'Contact Us',
    'consult.home.banner.button[1].label': 'Read Our Insights',
    'consult.home.banner.description': 'To learn more about how Fusion Consulting can help you with your next digital transformation, contact us or see our consultant insights.',
    'consult.home.hero.button[0].label': 'EXPLORE OUR SOLUTIONS',
    'consult.home.hero.button[1].label': 'EXPLORE OUR SERVICES',
    'consult.home.reasons.strategy': 'As companies continue to spur innovation at ever-growing rates, the optimization of process, organization, technical architectures, and business hierarchies is looked over. Fusion Consulting derives its vision from the overall Fusion Strategy where a methodical, yet quick process is followed to either transform or start your business. We belive in loosely coupled systems with high cohesion in both the technical and business realms and we work with you to decide the best course for your overall vision.',
    'consult.home.reasons.subtitle': ' ',
    'consult.home.reasons.title': 'Why Us',
    'consult.home.services.title': 'Our Services',
    'consult.home.services[0].description': 'Our Social Group focuses on connecting humanity. Whether its a marketing campaign, advertising, or technology that creates or improves a consumer ecosystem, our social engineers are visionary individuals with an affinity for creating relationships between your business and indviduals.',
    'consult.home.services[0].subtitle': 'Create consumer ecosystems that disrupt the industry',
    'consult.home.services[0].title': 'Social',
    'consult.home.services[1].description': 'Our Web Group orients itself as the premier application development team with a willingness and capability to create a seamless experience from user interface design to database management for our clients and the world.',
    'consult.home.services[1].subtitle': 'Our quest is to offer a seamless experience built atop optimal architectures.',
    'consult.home.services[1].title': 'Web',
    'consult.home.services[2].description': 'Our Web Group orients itself as the premier application development team with a willingness and capability to create a seamless experience from user interface design to database management for our clients and the world.',
    'consult.home.services[2].subtitle': 'Our quest is to offer a seamless experience built atop optimal architectures.',
    'consult.home.services[2].title': 'Data',
    'consult.home.services[3].description': 'Everything is data. Also, data is borne from other data. With the growing trends and potential intelligence explosion upon us, data management and services are becoming a necessity. Our Data Group will work with your team to ensure optimal solutions for all of your needs.',
    'consult.home.services[3].subtitle': 'Approach innovation with a structured thought process',
    'consult.home.services[3].title': 'Cloud',
    'consult.home.services[4].description': 'Cloud-based services are pervasive throughout every industry vertical. Our team empowers your organization to diminish capital expenses, increment business adaptability, and increase overall efficiency.',
    'consult.home.services[4].subtitle': 'Anticipate and respond to opportunities to improve',
    'consult.home.services[4].title': 'AI',
    'consult.home.services[5].description': 'Our Reality Group works to transform entertainment by employing the latest technologies and creative ideas.',
    'consult.home.services[5].subtitle': 'Anticipate and respond to opportunities to improve',
    'consult.home.services[5].title': 'Reality',
    'consult.home.video.title': 'Who We Are',

    

};