// NAVIGATION
export const NAV_TOGGLE = 'NAV_TOGGLE';

// CAREERS
export const CAREER_CHANGE = 'CAREER_CHANGE';
export const CAREER_CREATE = 'CAREER_CREATE';
export const CAREER_LOAD = 'CAREER_LOAD';
export const CAREER_REMOVE = 'CAREER_REMOVE';
export const CAREER_UNLOAD = 'CAREER_UNLOAD';
export const CAREER_UPDATE = 'CAREER_UPDATE';
export const CAREERS_FILTER = 'CAREERS_FILTER';
export const CAREERS_SEARCH = 'CAREERS_SEARCH';
export const CAREERS_LOAD = 'CAREERS_LOAD';
export const CAREERS_UNLOAD = 'CAREERS_UNLOAD';

// INSIGHTS
export const INSIGHT_CHANGE = 'INSIGHT_CHANGE';
export const INSIGHT_CREATE = 'INSIGHT_CREATE';
export const INSIGHT_LOAD = 'INSIGHT_LOAD';
export const INSIGHT_REMOVE = 'INSIGHT_REMOVE';
export const INSIGHT_UPDATE = 'INSIGHT_UPDATE';
export const INSIGHT_UNLOAD = 'INSIGHT_UNLOAD';
export const INSIGHTS_FILTER = 'INSIGHTS_FILTER';
export const INSIGHTS_LOAD = 'INSIGHTS_LOAD';
export const INSIGHTS_UNLOAD = 'INSIGHTS_UNLOAD';

// MESSAGE ACTIONS
export const MESSAGE_LOAD = 'MESSAGE_LOAD';
export const MESSAGE_UNLOAD = 'MESSAGE_UNLOAD';

// POLICIES
export const POLICIES_LOAD = 'POLICIES_LOAD';
export const POLICIES_UNLOAD = 'POLICIES_UNLOAD';
export const POLICY_CHANGE = 'POLICY_CHANGE';
export const POLICY_CREATE = 'POLICY_CREATE';
export const POLICY_LOAD = 'POLICY_LOAD';
export const POLICY_UNLOAD = 'POLICY_UNLOAD';
export const POLICY_UPDATE = 'POLICY_UPDATE';

// PRODUCTS
export const PRODUCTS_LOAD = 'PRODUCTS_LOAD';
export const PRODUCTS_UNLOAD = 'PRODUCTS_UNLOAD';

// SESSION
export const SESSION_END = 'SESSION_END';
export const SESSION_START = 'SESSION_START';

// STANDARDS
export const STANDARD_CHANGE = 'STANDARD_CHANGE';
export const STANDARD_CREATE = 'STANDARD_CREATE';
export const STANDARD_LOAD = 'STANDARD_LOAD';
export const STANDARD_REMOVE = 'STANDARD_REMOVE';
export const STANDARD_UNLOAD = 'STANDARD_UNLOAD';
export const STANDARD_UPDATE = 'STANDARD_UPDATE';
export const STANDARDS_LOAD = 'STANDARDS_LOAD';
export const STANDARDS_UNLOAD = 'STANDARDS_UNLOAD';

// STRATEGIES
export const STRATEGIES_LOAD = 'STRATEGIES_LOAD';
export const STRATEGIES_UNLOAD = 'STRATEGIES_UNLOAD';
export const STRATEGY_CHANGE = 'STRATEGY_CHANGE';
export const STRATEGY_CREATE = 'STRATEGY_CREATE';
export const STRATEGY_LOAD = 'STRATEGY_LOAD';
export const STRATEGY_REMOVE = 'STRATEGY_REMOVE';
export const STRATEGY_UNLOAD = 'STRATEGY_UNLOAD';
export const STRATEGY_UPDATE = 'STRATEGY_UPDATE';