// NAVIGATION
export const NAV_TOGGLE = 'NAV_TOGGLE';

// CAREERS
export const CAREERS_LOAD = 'CAREERS_LOAD';
export const CAREERS_UNLOAD = 'CAREERS_UNLOAD';

// INSIGHTS
export const INSIGHT_LOAD = 'INSIGHT_LOAD';
export const INSIGHTS_FILTER = 'INSIGHTS_FILTER';
export const INSIGHTS_LOAD = 'INSIGHTS_LOAD';
export const INSIGHTS_UNLOAD = 'INSIGHTS_UNLOAD';

// PRODUCTS
export const PRODUCTS_LOAD = 'PRODUCTS_LOAD';

// SESSION
export const SESSION_END = 'SESSION_END';
export const SESSION_START = 'SESSION_START';